### ISSUE TITLE
embed package

### ISSUE THREAD

**Issue by DanielRivasMD** [matsuyoshi30/germanium#1]
Hi. I wanted to try out your tool, but i get the following message when `go install` or `go get`: `font.go:4:2: package embed is not in GOROOT (/usr/local/Cellar/go/1.15.8/libexec/src/embed)`. Appreciate your help. Cheers

**Comment by matsuyoshi30** [comment]
Thanks for reporting. If you want to `go install` this package, you need to upgrade Go version to 1.16.

You can download the binary from https://github.com/matsuyoshi30/germanium/releases without upgrading Go.

**Comment by DanielRivasMD** [comment]
Thanks for your help. It does work flawlessly with Go 1.16. Closing the issue now.
