### ISSUE TITLE
Any plan to support chinese chars ?

### ISSUE THREAD

**Issue by Purelightme** [matsuyoshi30/germanium#3]
chinese chars can not be rendered normally.

test.go:
```
package main

import "fmt"

func main()  {
	fmt.Println("hello你好")
}

```

test.png:
![test](https://user-images.githubusercontent.com/16385534/109443779-65f1b100-7a76-11eb-91e3-b345ad9d8d1a.png)

**Comment by matsuyoshi30** [comment]
Thanks for reporting. I'll update for supporting CJK, so wait for a while please.

**Comment by matsuyoshi30** [comment]
@Purelightme HI. Now, you can generate an image from code by specifying the font that supports Chinese characters from your system.

`germanium --font 'Ricty-Regular' testdata/main.go`

![output](https://user-images.githubusercontent.com/16238709/109599717-028f7e00-7b5f-11eb-9331-eaceb702f93f.png)

**Comment by Purelightme** [comment]
@matsuyoshi30 Great.Very Thankful.
