### ISSUE TITLE
[Bug] Output flag only accepts relative paths and not absolute

### ISSUE THREAD

**Issue by AZMCode** [matsuyoshi30/germanium#34]
When passing the output flag an absolute path, it will always be insterpreted as relative

**Comment by matsuyoshi30** [comment]
Thanks for reporting @AZMCode .

Could you show me the result of executing the command when passing the output flag an absolute path?

**Comment by AZMCode** [comment]
I noticed I could not replicate when building from source, only from latest release.

When passing in an absolute path like `/tmp/hello` it would attempt to save to `$PWD/tmp/hello`

**Comment by matsuyoshi30** [comment]
I forgot to release a new version after fixing this issue. Thanks!
